# wowforever-classicui

**Stack:** unknown

## Quick Start

```bash
echo 'no check configured' && echo 'no test configured' && echo 'no lint configured'
```

## Workflow

# Magistr workflow

The maintained workflow lives in the generated project skills. Read
`.claude/skills/craft/SKILL.md` and its
`.claude/skills/craft/references/runtime.md` contract before substantial work.
Those files define shared state, tool routing, roadmap export policy, recorded
verification, recovery, and commit scope. The runtime includes the Claude host
adapter; other hosts use their own generated adapter.

Use the skill matching the user’s request:

- `/next` or `/roadmap`: resume an authorized in-progress chunk first, otherwise
  select one ready chunk, through the native research, plan, execute, verify,
  completion, and commit lifecycle. Follow next's recovery contract: inspect
  `roadmap_status` and `ship_status`, keep a matching unfinished objective and
  plan, and never restart completed tasks or replace conflicting active work.
- `/next-loop`: bounded fresh-session handoff; one complete chunk per
  agent session, then a new session before the next chunk. The native TUI
  loop owns automatic chaining.
- `/validate`: configured gates with accurate results and recording status.
- `/roadmap-refresh` or `/signals`: research and native state updates within
  the requested scope, without implementing the resulting features.
- `/init`: tailor project configuration without starting implementation.

A manual fix, review, configuration task, or planning discussion does not
itself authorize starting a roadmap chunk or an implementation loop. Preserve
unrelated user changes and active work. Store iteration narrative in native
reasoning and the local receipt, not always-loaded project instructions.

Keep native phase indicators current during an implementation iteration with
`magistr_set_phase`: `research`, `plan`, `execute`, `verify`, then `done` only
after the commit exists. Claude guard hooks remain additional enforcement;
follow the skills’ explicit recorded gates and lifecycle verification even
when the host does not run those hooks.


## Conventions

# Project Conventions

## Clean Code

- Single responsibility: one function does one thing.
- Functions stay short (under 30 lines). If longer, extract.
- Guard clauses over nested conditionals. Return early.
- Names describe intent: `getUserById` not `getData`, `isValid` not `check`.
- No magic numbers or strings. Use named constants.
- Delete dead code. Do not comment it out.

## Naming Consistency

- Pick one naming convention per category and apply it uniformly:
  - Functions and variables: `camelCase` or `snake_case` (match language idiom).
  - Types and classes: `PascalCase`.
  - Constants: `SCREAMING_SNAKE_CASE`.
- File names match the primary export or class they contain.
- Test files are co-located with source or in a parallel test directory.

## Error Handling

- Handle errors explicitly. Never silently swallow exceptions or error codes.
- Use the language's idiomatic error mechanism (exceptions, Result types, error codes).
- Add context when propagating errors — what operation failed and why.
- Validate inputs at system boundaries. Do not trust external data.

## Testing

- Write tests alongside implementation. At minimum: happy path, error path, edge cases.
- One assertion concept per test. Clear test names describe the scenario.
- Use the project's test framework. Follow its conventions for file naming and structure.
- Test error paths, not just success paths.
- Use temporary directories for filesystem tests. Never write to fixed paths.

## Dependencies

- Minimize dependency count. Prefer standard library solutions when reasonable.
- Pin dependency versions. Update deliberately, not automatically.
- Audit new dependencies for maintenance status and security.

## Security

- No secrets in code. Use environment variables or secret managers.
- Validate and sanitize all external input.
- Use parameterized queries for database access. No string concatenation.
- Follow the principle of least privilege for file access and API permissions.

## Code Organization

- Separate concerns: data access, business logic, and presentation in distinct layers.
- Keep modules focused. If a file exceeds 300 lines, consider splitting.
- Group related functionality together. Alphabetical ordering within groups.
- Public API surface should be minimal. Hide implementation details.


<!-- Auto-generated by magistr — DO NOT EDIT. Re-run `magistr init` to update. -->
# Tool Guide

## Codebase Navigation & Editing (workbench-mcp)

| Tool | Replaces | Purpose |
|------|----------|---------|
| `search` | grep/rg/find/ls/glob | Ranked hits grouped by file; `mode:` lexical (default), structural (ast-grep), references, files. |
| `map` | tree/ls -R | Pruned tree with entry points, declared commands, per-file symbol outlines. |
| `read` | cat/head/tail/sed -n | A file, a line range, or a symbol by name — with line anchors and a content hash. |
| `edit` | sed -i/codemods | Parse-verified diff: replace body, insert around symbol, rename, structural rewrite, anchored replace. |
| `files` | mv/cp/rm/mkdir | Import-aware moves and journaled deletes; undoable. |
| `run` | running tests/build/lint | One declared command from `workbench.toml [commands]`, failures as rows. |
| `script` | bash one-liners over many files | Typed Code Mode: reads live, writes queued into one reviewable diff. |
| `undo` | git checkout -- (own edits) | Rewind the journal one or more steps. |

Every call returns one envelope (`ok`, `results`, `freshness`, `budget`, `truncation`, `notes`). Read `.claude/skills/workbench-routing/SKILL.md` for the routing table and error recovery. Git stays in the shell.

Recommended workflow: `map` → `search` → `read` → `edit` (parse-verified) → `run` for the declared gates; `search mode:references` before touching shared code.

## Roadmap, Reasoning & Execution (think-and-ship)

| Family | Purpose | Key tools |
|--------|---------|-----------|
| `roadmap_*` | The long-horizon plan-of-plans: chunks with deps, acceptance and status. | `roadmap_status`, `roadmap_next`, `roadmap_get`, `roadmap_start_chunk`, `roadmap_complete_chunk`, `roadmap_add_chunk`, `roadmap_update_chunk`, `roadmap_export` |
| `ship_*` | The execution trace: objective, plan, actions, quality gates. | `ship_set_objective`, `ship_plan`, `ship_start`, `ship_record`, `ship_complete`, `ship_check`, `ship_finalize`, `ship_status` |
| `think_*` | The reasoning trace: record findings throughout the work, explore questions, and link conclusions to evidence. | `think_record_step`, `think_pin_step`, `think_trace_checkpoint`, `think_search_trace` |
| `signal_*` | Stakeholder signals: capture, research, surface, promote to the roadmap. | `signal_capture`, `signal_pending`, `signal_research`, `signal_promote` |

Served by the same `magistr` MCP server. A roadmap chunk is realized by a ship objective, motivated by think reasoning; the plan is `ship_plan` (there is no plan file) and `ROADMAP.md` is a generated view (`roadmap_export`), never the source of truth.

## Record findings while you work

The user should be able to follow what was learned, which alternatives were
checked, and why the work changed direction. Use `think_record_step` throughout
substantive work, not just to open and close an iteration. Record concise,
user-readable summaries of evidence and conclusions; do not write private
internal deliberation, tool transcripts, or an invented account after the work.

- Record a finding when research answers a consequential question, an approach
  is chosen over a credible alternative, a test changes the diagnosis, or a
  constraint changes the plan. State the question, evidence (source, code or
  check), conclusion, and next action. An execution log is not a substitute.
- For a concrete alternative, uncertain assumption, or diagnostic question that
  needs its own investigation, start a branch with `branch_from` set to the
  actual originating step and `branch_name` phrased as the question being
  explored. Omit `step_number` to allocate it. Read the returned `branch.id`.
- Continue that investigation with its exact `branch_id` on every follow-up
  finding. Do not accidentally append those findings to the main line or start
  a new branch for each observation. Parallel or nested investigations each
  keep their own question and recorded origin.
- When findings are used, record a main-line synthesis with `dependencies`
  pointing to the supporting branch steps. Then call `think_set_branch_status`
  with `status: "merged"` and `merged_into` set to that synthesis step.
  A rejected idea can still produce useful findings: mark the investigation
  merged when its findings informed the result. Use `abandoned` only for an
  investigation stopped without using its findings, and record why.
- Correct an earlier conclusion with `revises_step` and `revision_reason`;
  preserve the earlier record. Link related execution through `execution_ref`
  and `ship_record.think_step`. Use meaningful names in prose rather than raw
  identifiers. Omit confidence unless there is a defensible basis for it.
- Before closing, review investigations opened for this work. Record their
  conclusions and actual use, or leave them active with an explicit unresolved
  question and next action. Do not mark unfinished investigations merged.

Use branches for real investigations, not to satisfy a quota or decorate a
graph. Straightforward work can remain linear. Never invent alternatives,
evidence, outcomes, relationships, or confidence. Keep records brief enough to
read while the work is happening.


## Quality & Workflow (magistr)

| Tool | Purpose |
|------|---------|
| `magistr_gate` | Run quality gates (`all` / `check` / `test` / `lint` + custom); each gate is recorded through `ship_check`. |
| `magistr_format` | Run the project formatter. |
| `magistr_set_phase` | Announce workflow phase transitions. |
| `magistr_delete` | Delete files/directories (use instead of `rm`). |
| `magistr_list` | List directory contents. |

## Tool Preferences

- Use workbench `search`/`map` instead of Glob/find for file discovery.
- Use workbench `search` (lexical/structural/references) instead of Grep/grep.
- Use workbench `read` for exploration and `edit` for verified writes; built-in `Read`/`Edit` only when workbench is unavailable.
- Use workbench `run` for declared commands; `magistr_gate` runs the full gate set.
- Use the `roadmap_*` tools instead of editing `ROADMAP.md` — it is a generated view (`roadmap_export`).
- Record every gate through `ship_check` (`magistr_gate` forwards to it) — never a piped or self-reported result.
- Pass `autoApply: true` on a workbench `edit`/`files`/`script` write you intend to make — a confirm-gated write left unanswered is a dangling CONFIRM_REQUIRED, and under `magistr next-loop` there is no human to answer one.
- Use `magistr_delete` instead of `rm` in Bash.
- Do not spawn sub-agents — work directly in the current session.
