import {catalog} from "./releases.mjs";
const escape=value=>String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
export function installPage(){
 const published=catalog.installer;
 const download=published ? '<a class="primary" href="'+escape(published.url)+'">Download RikUI setup for Windows</a>' : '<p role="status">Windows setup is temporarily unavailable. <a href="'+escape(catalog.releasesUrl)+'">See published releases</a>.</p>';
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Install RikUI · WoW Forever</title><meta name="description" content="Install RikUI with locally prepared quest guidance and navigation for your current WoW Forever client."><link rel="stylesheet" href="/site.css"></head><body><a class="skip" href="#main">Skip to content</a><header class="site-header wrap"><a class="brand" href="/">RikUI<span>FOR WOW FOREVER</span></a><nav aria-label="Main navigation"><a href="/docs">Guides</a><a href="/docs/options">Customize in game</a></nav></header><main id="main" tabindex="-1" class="wrap section prose"><p class="eyebrow">WINDOWS SETUP · FOREVER BETA</p><h1>Your quest guide and routes</h1><p class="lead">Setup finds your current Forever game, gets quest information from its publisher, and prepares supported routes on your computer.</p><div class="actions">${download}</div><p>RikUI ${escape(catalog.latest)}. Requires an installed current Forever client with English game text (enUS), Windows 10 or later, an internet connection and space for preparation and backups. Everything setup needs is included.</p>
 <h2>Four simple steps</h2><ol><li><strong>Find your game.</strong> Open setup. It checks your installed game against the current Forever version. Use Browse if needed. If versions differ, update Forever in Battle.net and choose Check again.</li><li><strong>Get quest information.</strong> Choose Prepare and install. Setup downloads quest and holiday information from <a href="https://github.com/Questie/QuestieDB">QuestieDB</a>. You do not need to install QuestieDB first.</li><li><strong>Prepare routes.</strong> Setup reads your game files and prepares routes on your computer. It shows progress and elapsed time. First preparation can take substantial time; you can pause and resume.</li><li><strong>Ready to play.</strong> Close WoW when prompted. Setup checks the prepared files, installs them and keeps a backup. Restart WoW fully and enable RikUI.</li></ol>
 <h2>Space and preparation time</h2><p>Allow <strong>16 GiB free</strong> for first preparation. Setup keeps temporary files compact to reduce disk use. It checks space before starting and while working. Previous generations and backups use additional space. Choose <strong>Preparation folder</strong> to use another drive. Existing work is preserved; keep its folders available for updates. Your computer, connection and future client changes affect preparation time and space.</p><details><summary>Why does preparation take time?</summary><p>First preparation can take an hour or more. Setup downloads quest information, reads your game files and prepares walkable routes. It adjusts its workload to your computer and shows elapsed time as it works. Updates can reuse completed work after checking it. Pause setup whenever you need to; completed work is kept for the next run.</p></details>
 <h2>What coverage means</h2><p><strong>Currently verified regions:</strong> Eastern Kingdoms, Kalimdor, Zephras Isle, Darkspear Islands, Alterac Valley, Warsong Gulch and Arathi Basin. Navigation for other maps and instances is not established. The quest database includes 5,009 quests and accounts for supported character differences. Another 2,324 quest IDs in the current game files lack complete guide information.</p><p>The guide includes quest objectives, known locations and requirements for your character. <strong>Guide language: English game text (enUS).</strong> Guides in other languages are not currently supported. Use English game text for quest guidance. Some new quests may not yet have complete instructions or locations. Routes may be unavailable on certain floors or during phased quests; the guide will tell you when information is missing.</p><p>Setup installs the guide only when all supported regions are ready and checked. Pausing keeps completed work so you can resume later. The View details button lists your verified build, quest coverage, prepared regions and backups.</p>
 <h2>Updates and recovery</h2><p>Setup checks for RikUI updates, new Forever versions and updated quest information when it opens. A daily Windows task also checks automatically. When needed, setup prepares updated data and checks existing files before reusing them. Guidance for an older game version is withheld until compatible data is ready.</p><p>Setup can find your game if its name or folder changes for release. If it finds more than one matching game, choose the one you play.</p><p>Paused preparation stays paused until you choose Resume setup. Download or preparation problems retain your existing installation and completed work. Check your connection or free disk space, then retry. Restore backup returns to the previous RikUI installation. WoW settings and unrelated addons are preserved. Backups remain in Interface/RikUI-backups.</p>
 <h2>Interface-only addon ZIP</h2><p>The <a href="${escape(catalog.releasesUrl)}">public addon release</a> can be installed manually in the current game's Interface/AddOns folder. This ZIP includes the interface; setup prepares the quest guide and routes separately. Use Windows setup for the locally generated quest guide and navigation.</p><p><a href="/docs/installation">Installation guide</a> · <a href="/docs/quests">Quest guidance</a> · <a href="https://github.com/rik-wow/RikUI/issues">Report a problem</a></p></main><footer class="wrap"><p>RikUI is an independent fan project for WoW Forever.</p></footer></body></html>`;
}
