import {catalog} from "./releases.mjs";
const escape=value=>String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
export function installPage(){
 const published=catalog.installer;
 const download=published ? '<a class="primary" href="'+escape(published.url)+'">Download RikUI setup for Windows</a>' : '<p role="status">The verified Windows setup release is being prepared. <a href="'+escape(catalog.releasesUrl)+'">See published releases</a>.</p>';
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Install RikUI · WoW Forever</title><meta name="description" content="Install RikUI with locally prepared quest guidance and navigation for your current WoW Forever client."><link rel="stylesheet" href="/site.css"></head><body><a class="skip" href="#main">Skip to content</a><header class="site-header wrap"><a class="brand" href="/">RikUI<span>FOR WOW FOREVER</span></a><nav aria-label="Main navigation"><a href="/docs">Guides</a><a href="/docs/options">Customize in game</a></nav></header><main id="main" tabindex="-1" class="wrap section prose"><p class="eyebrow">WINDOWS SETUP · FOREVER BETA</p><h1>Your quest guide and routes</h1><p class="lead">Setup finds your current Forever game, gets quest information from its publisher, and prepares supported routes on your computer.</p><div class="actions">${download}</div><p>RikUI ${escape(catalog.latest)}. Requires an installed current Forever client, Windows 10 or later, an internet connection and space for generation and backups. Setup includes its build tools. You do not need to install Git, Python, Node or a database.</p>
 <h2>Four simple steps</h2><ol><li><strong>Find your game.</strong> Open setup. It checks your installed game against the current Forever version. Use Browse if needed. If versions differ, update Forever in Battle.net and choose Check again.</li><li><strong>Get quest information.</strong> Choose Prepare and install. Setup obtains <a href="https://github.com/Questie/QuestieDB">QuestieDB</a> source and holiday inputs separately from their publishers. An installed QuestieDB addon ZIP is not used as a source checkout.</li><li><strong>Prepare routes.</strong> Terrain and quest membership come from your own game files. Setup shows completed jobs and elapsed time. You can pause and resume. First preparation takes substantial time; it is a local build.</li><li><strong>Ready to play.</strong> Close WoW when prompted. Setup installs only after verification, retains backups, and verifies installed bytes. Restart WoW fully and enable RikUI.</li></ol>
 <h2>Space and preparation time</h2><p>Allow at least 80 GiB free for preparation, plus room for retained previous generations and installation backups. The space check applies to the local setup cache drive. Choose Preparation folder in setup to use another drive; existing work on the previous drive is retained. Measured reference cost and supported regional coverage are included with the release; your computer and future client updates can differ.</p>
 <h2>What coverage means</h2><p>The guide uses all supported provider quest, NPC, item, object, objective, prerequisite, player-variant and localization inputs. Current client quest IDs without provider details remain unknown. Provider information can lag the server. Unknown floors, phases, triggers, physics or projections are explicit; they are not invented as routes.</p><p>Preparation is incomplete until all supported generation and verification finish. Partial work is retained for resume and is never advertised as a complete installation. The View details button lists your verified build, quest coverage, prepared regions and backups.</p>
 <h2>Updates and recovery</h2><p>Setup checks its published update channel and current client, provider and schema inputs at startup and when updating. A daily Windows task repeats these checks. Changed inputs rebuild affected outputs; unchanged outputs are reused only after their recorded bytes and compatibility verify. A new client build requires current data. Stale guidance is withheld.</p><p>The release transition discovers the matching client executable, product and directory from your WoW storage folder. It does not assume the beta folder survives launch. If more than one client matches, choose the right game folder.</p><p>Paused preparation stays paused until you choose Resume setup. Publisher or build failures retain your existing installation and completed work. Check your connection or free disk space, then retry. Restore backup restores the previous owned addon files. WoW settings and unrelated addons are preserved. Backups remain in Interface/RikUI-backups.</p>
 <h2>Interface-only addon ZIP</h2><p>The <a href="${escape(catalog.releasesUrl)}">public addon release</a> can be installed manually in the current game's Interface/AddOns folder. It does not contain imported quest datasets or extracted geometry. Use Windows setup for the locally generated quest guide and navigation.</p><p><a href="/docs/installation">Installation guide</a> · <a href="/docs/quests">Quest guidance</a> · <a href="https://github.com/rik-wow/RikUI/issues">Report a problem</a></p></main><footer class="wrap"><p>Independent fan project. Reference data and extracted client geometry are obtained separately and kept on your computer. Future beta builds are verified when available.</p></footer></body></html>`;
}
