import { mark, icon, combat, quests, setup, inspector } from "./previews.mjs";
export const page = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>RikUI — Your interface for WoW Forever</title>
<meta name="description" content="A complete, modular interface for WoW Forever. Explore RikUI’s combat HUD, quest planner and setup tools.">
<meta name="theme-color" content="#0c1016"><link rel="canonical" href="https://rikwow.com/">
<link rel="stylesheet" href="/site.css"><script src="/site.js" defer></script></head>
<body><a class="skip" href="#main">Skip to content</a>
<header class="site-header"><a class="brand" href="/" aria-label="RikUI home">${mark}<span>Rik<span class="brand-ui">UI</span></span></a><span class="header-divider"></span><span class="for-forever">FOR WOW FOREVER</span>
<nav aria-label="Main navigation"><a href="#interface">The interface</a><a href="#features">Features</a><a href="#install">Get started</a></nav><a class="source-link" href="https://github.com/rik-wow/RikUI">GitHub <span aria-hidden="true">↗</span></a></header>
<main id="main" tabindex="-1"><section class="hero wrap" aria-labelledby="headline">
<div class="hero-copy"><div class="eyebrow"><span class="status-dot"></span> RIKUI <span class="slash">/</span> FOREVER BETA</div><h1 id="headline">Your interface.<br><span>Rebuilt for Forever.</span></h1></div>
<div class="hero-intro"><p>A complete UI for your next adventure.<br>Combat, questing and the everyday details,<br class="desktop-break"> brought into one consistent interface.</p><div class="hero-actions"><a class="button primary" href="#interface">Explore the interface ${icon('arrow')}</a><a class="quiet-link" href="#install">Get started <span>↗</span></a></div></div>
</section>
<section class="showcase wrap" id="interface" aria-labelledby="preview-heading">
<div class="showcase-top"><h2 id="preview-heading">${mark} THE RIKUI INTERFACE</h2><span class="preview-disclosure">Illustrated previews · sample content</span></div>
<div class="toolbar"><div class="tabs" role="tablist" aria-label="Interface previews">
<button id="tab-combat" type="button" role="tab" aria-selected="true" aria-controls="panel-combat" data-view="combat">${icon('target')} Combat HUD</button>
<button id="tab-quests" type="button" role="tab" aria-selected="false" aria-controls="panel-quests" tabindex="-1" data-view="quests">${icon('quest')} Quest planner</button>
<button id="tab-setup" type="button" role="tab" aria-selected="false" aria-controls="panel-setup" tabindex="-1" data-view="setup">${icon('settings')} Setup</button></div>
<div class="accent-picker" role="group" aria-label="Preview class accent"><span>CLASS COLOR</span>
<button class="swatch mage" type="button" data-accent="mage" aria-label="Mage accent" aria-pressed="true"><i></i></button><button class="swatch warlock" type="button" data-accent="warlock" aria-label="Warlock accent" aria-pressed="false"><i></i></button><button class="swatch druid" type="button" data-accent="druid" aria-label="Druid accent" aria-pressed="false"><i></i></button><button class="swatch warrior" type="button" data-accent="warrior" aria-label="Warrior accent" aria-pressed="false"><i></i></button></div></div>
<div class="preview-area" data-theme="mage">
<div id="panel-combat" class="preview-panel" role="tabpanel" aria-labelledby="tab-combat" tabindex="0">${combat}${inspector('combat')}</div>
<div id="panel-quests" class="preview-panel" role="tabpanel" aria-labelledby="tab-quests" tabindex="0" hidden>${quests}${inspector('quests')}</div>
<div id="panel-setup" class="preview-panel" role="tabpanel" aria-labelledby="tab-setup" tabindex="0" hidden>${setup}${inspector('setup')}</div></div>
<div class="showcase-footer"><span><i></i> DESIGNED AROUND YOUR CHARACTER</span><span>Modular. Movable. Yours.</span></div>
<noscript><p class="no-script">The combat preview is shown above. Explore the <a href="https://github.com/rik-wow/RikUI/blob/main/docs/questplanner.md">quest planner</a> and <a href="https://github.com/rik-wow/RikUI/blob/main/docs/wizard.md">setup guide</a>.</p></noscript></section>
<section class="features-section wrap" id="features" aria-labelledby="features-heading"><div class="section-heading"><div><span class="eyebrow">BEYOND THE ACTION BARS</span><h2 id="features-heading">The whole interface.<br>The same attention to detail.</h2></div><p>From the first pull to your last bag slot.<br>Enable the modules you want and arrange<br class="desktop-break"> them around the way you play.</p></div>
<div class="feature-lines"><a href="https://github.com/rik-wow/RikUI/blob/main/docs/unitframes.md"><span class="feature-number">01</span>${icon('shield')}<div><h3>Unit frames &amp; nameplates</h3><p>Player, target, party and raid frames with clear health, power and aura displays.</p></div><span class="feature-arrow">↗</span></a>
<a href="https://github.com/rik-wow/RikUI/blob/main/docs/bags.md"><span class="feature-number">02</span>${icon('spell')}<div><h3>Bags, loot &amp; the auction house</h3><p>Combined bags with search, readable loot cards and a dedicated auction interface.</p></div><span class="feature-arrow">↗</span></a>
<a href="https://github.com/rik-wow/RikUI/blob/main/docs/chat.md"><span class="feature-number">03</span>${icon('settings')}<div><h3>All the little things</h3><p>Chat history, timestamps, a square minimap and consistent menus, tooltips and windows.</p></div><span class="feature-arrow">↗</span></a></div></section>
<section class="setup-section" id="install" aria-labelledby="start-heading"><div class="wrap start-grid"><div><span class="eyebrow">START YOUR NEXT SESSION</span><h2 id="start-heading">A place for everything.<br>A setup of your own.</h2><p>RikUI is open source and in active development for WoW Forever. Start with the guide and build it locally.</p><a class="button primary" href="https://github.com/rik-wow/RikUI/blob/main/installer/README.md">Open the installation guide ${icon('arrow')}</a><p class="release-note"><span class="status-dot"></span> Public Windows installer coming later.<br>Source and local build instructions are available now.</p></div>
<ol class="start-steps"><li><span>01</span><div><h3>Install RikUI</h3><p>Use the complete local build instructions, then enable RikUI in your AddOns list.</p></div></li><li><span>02</span><div><h3>Choose your starting point</h3><p>Open <code>/rik setup</code>. Pick a preset and review exactly what it will change.</p></div></li><li><span>03</span><div><h3>Make room for your habits</h3><p>Use <code>/rik move</code> to arrange frames and <code>/rik config</code> to choose your modules.</p></div></li></ol></div></section>
<section class="faq wrap" aria-labelledby="faq-heading"><div><span class="eyebrow">BEFORE YOU LOG IN</span><h2 id="faq-heading">A few good questions.</h2></div><div class="faq-list"><details><summary>Which version of WoW is this for?<span>+</span></summary><p>RikUI targets the WoW Forever beta. It is not advertised as compatible with Retail, Classic Era or other clients.</p></details><details><summary>Will it change my keybindings?<span>+</span></summary><p>Installing RikUI alone does not change your bindings. Setup lets you review and choose which changes to apply. The last setup can be undone with <code>/rik undo</code>.</p></details><details><summary>Can I turn individual parts off?<span>+</span></summary><p>Yes. Choose modules in <code>/rik config</code>, move frames with <code>/rik move</code> and save different profiles. Some changes require a UI reload.</p></details><details><summary>Does quest guidance cover everything?<span>+</span></summary><p>Coverage depends on the installed quest and road data. Missing or unverified objectives, locations and paths remain explicit. See the <a href="https://github.com/rik-wow/RikUI/blob/main/docs/questplanner.md">coverage guide</a>.</p></details></div></section>
</main><footer class="wrap"><a class="brand" href="/" aria-label="RikUI home">${mark}<span>Rik<span class="brand-ui">UI</span></span></a><p>Made for the way you play.<br><small>Independent project. Not affiliated with Blizzard Entertainment.</small></p><div><a href="https://github.com/rik-wow/RikUI">Source ↗</a><a href="https://github.com/rik-wow/RikUI/issues">Feedback ↗</a><a href="https://github.com/rik-wow/RikUI/blob/main/LICENSE">License ↗</a></div></footer></body></html>`;
