export const styles = `
:root{color-scheme:dark;--bg:#0b1115;--panel:#141d23;--ink:#f1eee6;--muted:#abb5b7;--gold:#edc88b;--line:#344047;--accent:#8bc6c2;font:16px/1.6 system-ui,sans-serif}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink)}a{color:inherit;text-underline-offset:.25em}button,input,select,textarea{font:inherit}button,a.primary{cursor:pointer}button,select,input,textarea{background:#18242c;color:var(--ink);border:1px solid #53616a;border-radius:5px}button{padding:.55rem .85rem;min-height:44px}input,select,textarea{padding:.6rem;width:100%;max-width:100%}input[type=checkbox]{width:auto;accent-color:var(--gold);margin-right:.55rem}textarea{resize:vertical;overflow-wrap:anywhere;font:12px/1.5 ui-monospace,monospace}label{display:block;font-size:.88rem;margin:.6rem 0}label>select,label>input:not([type=checkbox]),label>textarea{display:block;margin-top:.3rem}button:hover,a.primary:hover{border-color:var(--gold);background:#26353b}button:disabled{opacity:.5;cursor:default}:focus-visible{outline:3px solid var(--gold);outline-offset:4px}[hidden]{display:none!important}
.wrap{width:min(1440px,calc(100% - 64px));margin-inline:auto}.site-header{display:flex;align-items:center;justify-content:space-between;padding:28px 0;gap:32px;border-bottom:1px solid var(--line)}.brand{font-size:30px;letter-spacing:-1px;font-weight:850;text-decoration:none;line-height:1}.brand span{display:block;font-size:9px;letter-spacing:2px;color:var(--muted);margin-top:9px}nav{display:flex;align-items:center;gap:32px}nav a{text-decoration:none;font-size:14px}.install-link{border:1px solid var(--line);padding:10px 16px;border-radius:5px}
h1,h2,h3{line-height:1.1;letter-spacing:-.035em}h1{font-size:clamp(40px,4.7vw,72px);margin:20px 0}h2{font-size:clamp(27px,2.5vw,40px)}h3{font-size:25px}.eyebrow{color:var(--gold);font-size:11px;font-weight:750;letter-spacing:.16em}.lead{font-size:20px;color:#c4cecf;max-width:630px}.fine,figcaption{font-size:12px;line-height:1.55;color:var(--muted)}.hero{display:grid;grid-template-columns:1fr 1.2fr;gap:64px;align-items:center;padding-block:86px}.hero figure{margin:0;transform:perspective(1400px) rotateY(-4deg);border:1px solid var(--line);border-radius:8px;overflow:hidden;background:#10191f;box-shadow:0 25px 80px #0008}.hero figure img{width:100%;display:block}.hero figcaption{padding:12px 20px}.actions{display:flex;align-items:center;flex-wrap:wrap;gap:12px;margin:22px 0}.primary{display:inline-block;color:#152026;background:var(--gold);border:1px solid var(--gold);padding:12px 20px;font-weight:750;text-decoration:none;border-radius:5px}.primary:hover{color:var(--ink)}.section{padding-block:55px}.section-heading{display:flex;align-items:end;justify-content:space-between;gap:24px;margin-bottom:30px}.section-heading h2{margin-bottom:0}.setup-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:24px}.setup-card{border:1px solid var(--line);border-radius:7px;overflow:hidden;background:#121c22}.setup-card a{display:block;text-decoration:none}.setup-card img{width:100%;display:block;border-bottom:1px solid var(--line)}.setup-card div{padding:25px}.setup-card h3{margin:12px 0}.setup-card p{color:var(--muted);max-width:480px}.text-link{color:var(--gold);font-size:14px}.setup-card a:hover{background:#1a272e}.journey{display:grid;grid-template-columns:repeat(3,1fr);gap:42px;border-top:1px solid var(--line)}.journey span{font-size:11px;letter-spacing:.1em;color:var(--gold)}.journey p{color:var(--muted)}.cta{border:1px solid var(--line);border-radius:8px;text-align:center;margin-block:36px;background:#142129}.cta p{max-width:760px;margin:24px auto}.cta a{margin:12px}.showcase{margin:32px 0;border:1px solid var(--line)}.showcase img{display:block;width:100%}.showcase figcaption{padding:15px}.pack-details{display:grid;grid-template-columns:1fr 1fr;gap:64px}.prose{max-width:900px}.prose li{margin-bottom:16px}.prose h2{margin-top:45px}code{color:var(--gold)}footer{padding-block:48px;border-top:1px solid var(--line);margin-top:64px;font-size:14px}.skip{position:absolute;top:-80px;left:16px;z-index:20;padding:12px;background:var(--gold);color:#111}.skip:focus{top:12px}
@media(max-width:1100px){.hero{gap:30px;grid-template-columns:1fr 1fr}nav{gap:18px}.wrap{width:calc(100% - 40px)}}
@media(max-width:760px){.wrap{width:calc(100% - 28px)}.site-header{padding:22px 0;gap:16px;flex-wrap:wrap}nav{width:100%;gap:18px;flex-wrap:wrap}nav a{font-size:12px}.hero{grid-template-columns:1fr;padding-block:45px;gap:28px}.hero figure{transform:none}.setup-grid,.journey,.pack-details{grid-template-columns:1fr;gap:22px}.section{padding-block:35px}footer{margin-top:35px}.lead{font-size:18px}.cta{padding-inline:20px}}

@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;animation:none!important;transition:none!important}.hero figure{transform:none}}

.preview-stage{position:relative}.mover-layer{position:absolute;inset:0;pointer-events:none}.studio-mover{position:absolute;pointer-events:auto;border:1px dashed #7996a8;border-radius:2px;background:rgba(100,145,170,.035);padding:0;min-height:0;touch-action:none}.studio-mover span,.studio-reservation span{position:absolute;left:0;top:0;max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;background:#15222fe8;color:#deebf4;font-size:11px;line-height:15px;padding:0 3px;pointer-events:none}.studio-mover:hover{background:rgba(100,145,170,.10)}.studio-mover.conflict:hover{background:#f447542b}.studio-mover.selected{border:2px solid #ecc98a;z-index:3}.studio-mover.selected span{background:#604d25;color:#fff1ce}.studio-mover.conflict,.studio-reservation.conflict{border:2px solid #ff6f76;background:#f4475420}.studio-mover.conflict span,.studio-reservation.conflict span{background:#7e2432;color:#fff}.studio-mover:focus-visible{outline:3px solid #75cedb;outline-offset:2px;z-index:4}.studio-reservation{position:absolute;border:1px dotted #78bfca;background:#65c7d518;pointer-events:none}.character-area{border:1px dashed #8bc6c280;background:transparent}.character-area small{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);white-space:nowrap;color:#afc5c9;background:#0c1117dc;padding:2px 6px;font-size:clamp(7px,.7vw,11px)}.character-area small:before{content:'+';display:block;text-align:center;font:20px/1 system-ui}.character-area>span{background:#15222f;color:#b7d4d7}.preview-options{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin:10px 0}.preview-options label{display:flex;gap:5px;align-items:center;font-size:13px}.frame-list{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:6px;padding:10px 0}.frame-list button{min-height:44px;text-align:left}.frame-list button[aria-pressed=true]{border-color:#ecc98a}.fit-conflict{display:block;width:100%;text-align:left;border-color:#ff6f76;margin:6px 0;min-height:44px}.preview-stage canvas{display:block}.studio-mover[hidden]{display:none}

.studio-heading{display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:0 24px;padding:24px 0 12px}.studio-heading h1{font-size:32px;margin:8px 0}.studio-heading p{margin:4px 0;font-size:14px;color:var(--muted)}#studio-status{flex-basis:100%;min-height:24px;color:var(--gold);font-size:13px}
.studio-layout{display:grid;grid-template-columns:340px minmax(0,1fr);gap:20px;align-items:start}.studio-steps{grid-column:1/-1;display:grid;grid-template-columns:repeat(3,1fr);gap:8px;border-bottom:1px solid var(--line);padding-bottom:16px}.studio-steps button{text-align:left;border-color:transparent;background:transparent;color:var(--muted);font-weight:650}.studio-steps span{display:inline-grid;place-items:center;width:27px;height:27px;border:1px solid var(--line);border-radius:50%;margin-right:8px;font-size:12px}.studio-steps button[aria-current=step]{background:#202a30;color:var(--ink);border-color:var(--gold)}.studio-steps button[aria-current=step] span{background:var(--gold);color:var(--bg)}
.studio-controls,.studio-workspace{min-width:0}.studio-panel{background:#141d23;border:1px solid var(--line);border-radius:8px;padding:20px;font-size:14px}.studio-panel h2{font-size:23px;letter-spacing:-.025em;margin:0 0 12px}.studio-panel h2:focus{outline:none}.studio-panel p{color:var(--muted);font-size:13px;line-height:1.55}.studio-panel label{font-size:13px}.studio-panel button{font-size:13px}.studio-panel details{border-top:1px solid var(--line);margin-top:18px;padding-top:8px}.studio-panel summary{font-size:13px}.studio-panel .actions{gap:8px;margin:14px 0}.studio-continue{width:100%;margin-top:20px}.studio-pack-cards{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:18px 0}.studio-pack-cards button{padding:0;overflow:hidden;text-align:left;background:#10191f;border-color:var(--line)}.studio-pack-cards img{display:block;width:100%;aspect-ratio:16/9;object-fit:cover}.studio-pack-cards strong{display:block;padding:7px 10px;font-size:13px}.studio-pack-cards button[aria-pressed=true]{border:2px solid var(--gold)}.studio-pack-cards button[aria-pressed=true] strong{color:var(--gold)}
.studio-tabs{display:flex;gap:4px;margin-bottom:18px;border-bottom:1px solid var(--line)}.studio-tabs button{flex:1;border:0;border-bottom:2px solid transparent;border-radius:0;background:transparent;padding:8px 4px;color:var(--muted)}.studio-tabs button[aria-selected=true]{color:var(--gold);border-bottom-color:var(--gold)}.parts{display:grid;grid-template-columns:1fr 1fr;gap:4px}.parts label{gap:2px!important;padding:6px!important}.parts small{display:none!important}.parts label{display:flex;align-items:center;gap:10px;padding:8px;background:#10191f;border:1px solid #243139;border-radius:5px;margin:2px 0;cursor:pointer}.parts label:has(input:checked){border-color:#577471}.parts input{flex:none}.parts strong{font-size:13px;font-weight:600}.parts small{display:block;font-size:11px;color:var(--muted)}.setting-note{padding:12px;background:#10191f;border-radius:5px}
.editor-toolbar{display:flex;gap:8px;align-items:center;margin-bottom:12px}.editor-toolbar>div{flex:1;min-width:0}.editor-toolbar p{margin:3px 0;font-size:13px;color:var(--gold);overflow-wrap:anywhere}.editor-toolbar button{font-size:12px}.scene-toolbar{display:grid;grid-template-columns:1fr 1fr 1.2fr;gap:12px;margin-bottom:12px}.scene-toolbar label{font-size:12px;margin:0}.scene-toolbar select{font-size:12px;padding:8px;min-height:40px}.preview-shell{overflow:auto;border:1px solid var(--line);border-radius:7px;background:#0c1117}.preview-stage{width:calc(var(--fit-width,100%) * var(--preview-zoom,1));border:0;border-radius:0;box-shadow:none}.preview-stage canvas{width:100%;height:auto;display:block;touch-action:none}.preview-options{gap:10px}.preview-options button,.preview-options label{font-size:12px}.preview-options label:last-child{margin-left:auto}.preview-options select{width:80px;padding:5px;display:inline-block;min-height:36px;margin-left:6px}.preview-caption{display:flex;align-items:center;flex-wrap:wrap;gap:10px;padding:8px 0}.preview-caption button{font-size:12px;min-height:36px;padding:5px 9px}.fit-badge{font-size:12px;color:#a6d5c0;padding:4px 8px;border:1px solid #345648;border-radius:5px}.fit-badge.issue{color:#ffc28e;border-color:#95665b}.preview-notes{border-top:1px solid var(--line);padding-top:5px}.preview-notes summary{font-size:12px;color:var(--muted)}.preview-notes p{max-width:740px}
.frame-controls{display:flex;gap:8px;margin:14px 0}.frame-controls button{flex:1;font-size:21px;padding:4px}.frame-list{grid-template-columns:1fr}.frame-list button{font-size:12px}.review-panel{margin:0}.review-panel #ownership{font-size:12px;overflow-wrap:anywhere}.review-panel #fit-status{color:#a6d5c0}.review-panel #fit-status.issue{color:#ffc28e}.review-panel #export-help{color:var(--ink)}.fit-conflict{overflow-wrap:anywhere;font-size:12px}.issue{color:#ffc28e;border-left:3px solid #ffc28e;padding-left:12px}#geometry{font:11px/1.6 ui-monospace,monospace;color:var(--gold)}#result-panel{margin:18px 0;padding-top:10px;border-top:1px solid var(--line)}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:11px;max-height:260px;overflow:auto}summary{cursor:pointer;padding:9px 0;color:var(--gold)}.studio-fallback{padding:22px 0;color:var(--muted);font-size:13px}
@media(max-width:1100px){.studio-layout{grid-template-columns:310px minmax(0,1fr)}.scene-toolbar{grid-template-columns:1fr 1fr}.scene-toolbar label:last-child{grid-column:1/-1}.studio-steps button{font-size:13px}.preview-options label:last-child{margin-left:0}}
@media(max-width:760px){.studio-layout{grid-template-columns:1fr;gap:16px}.studio-steps{gap:4px;position:sticky;top:0;background:var(--bg);z-index:8;padding-block:8px}.studio-steps button{font-size:12px;padding:8px 4px;text-align:center}.studio-steps span{display:block;margin:0 auto 5px}.studio-controls{display:block;grid-row:auto}.studio-workspace{grid-row:auto}.studio-panel{padding:18px}.studio-pack-cards{grid-template-columns:repeat(4,1fr)}.studio-pack-cards strong{font-size:11px;padding:6px}.scene-toolbar{grid-template-columns:1fr 1fr 1fr;gap:6px}.scene-toolbar label:last-child{grid-column:auto}.scene-toolbar select{font-size:11px;padding:5px}.editor-toolbar{display:grid;grid-template-columns:minmax(0,1fr) auto auto}.editor-toolbar>div{min-width:0}.studio-heading h1{font-size:30px}.preview-options{gap:8px}.preview-options label{font-size:11px}.preview-caption .fine{flex-basis:100%}}
@media(max-width:430px){.studio-pack-cards{grid-template-columns:1fr 1fr}.scene-toolbar{grid-template-columns:1fr 1fr}.scene-toolbar label:last-child{grid-column:1/-1}}

.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip-path:inset(50%);white-space:nowrap;border:0}.ui-scale-control{grid-column:1/-1;display:grid;grid-template-columns:80px minmax(0,1fr);gap:4px 12px;align-items:center}.ui-scale-inputs{display:flex;gap:8px;align-items:center;min-width:0}.ui-scale-inputs input[type=range]{flex:1;min-width:44px;width:0;padding:0;accent-color:var(--gold);min-height:44px}.ui-scale-inputs input[type=number]{width:76px;min-height:44px;padding:5px;font-size:13px}.ui-scale-inputs button{min-height:44px;padding:5px 10px;font-size:12px}.ui-scale-control p{grid-column:1/-1;margin:0}.ui-scale-control>label{grid-column:auto!important}.ui-scale-control .sr-only{margin:0}.ui-scale-inputs span{font-size:12px;color:var(--muted)}@media(max-width:760px){.ui-scale-control{grid-template-columns:1fr;gap:4px}.ui-scale-control label{grid-column:auto!important}.ui-scale-inputs input[type=number]{width:72px}}

.module-browser{border-top:1px solid var(--line);margin-top:18px;padding-top:18px}.module-browser h3{font-size:18px;margin:0}.module-cards{display:grid;grid-template-columns:1fr 1fr;gap:10px;max-height:470px;overflow:auto;overscroll-behavior:contain;padding:5px 5px 10px}.module-card{background:#0e171d;border:1px solid #344047;border-radius:6px;min-width:0;padding:8px}.module-card>strong{display:block;font-size:12px;line-height:1.35;min-height:32px}.module-card>label{display:flex;align-items:center;gap:4px;min-height:44px;margin:0}.module-card input{flex:none;width:30px;height:18px}.module-card .fine{font-size:10px;margin:0 0 8px}.module-card>a{font-size:11px;color:var(--gold)}.module-visual{display:block;width:100%;min-height:74px;padding:0;background:#0c1117;margin-bottom:8px;overflow:hidden}.module-visual canvas{display:block;width:100%;height:auto}.module-visual img{display:block;width:100%;height:80px;object-fit:contain}.module-visual>span{font-size:11px;display:block;padding:8px}.module-visual:disabled{opacity:1}.module-off .module-visual{opacity:.4}.module-off{border-style:dashed}.module-blocked{border-color:#ffc28e}.selected-feature{display:grid;grid-template-columns:1fr auto;gap:5px 16px;border:1px solid var(--line);border-radius:6px;padding:12px;margin:12px 0;background:var(--panel)}.selected-feature strong{font-size:13px;align-self:center}.selected-feature label{margin:0;min-height:44px;display:flex;align-items:center;gap:8px}.selected-feature p{margin:0}.selected-feature a{font-size:12px;color:var(--gold)}.studio-mover.disabled{border-color:#82909c;background:#82909c10}.studio-mover.disabled span{color:#c0c8cc;background:#26323c}@media(max-width:760px){.module-cards{max-height:400px}.selected-feature{grid-template-columns:1fr}.module-card .fine{font-size:11px}}
.precision-bar{display:none}.drag-outline{position:absolute;pointer-events:none;border:2px dashed #75cedb;background:#75cedb10;z-index:6}.drag-outline[hidden]{display:none}
.studio-layout.precision-workspace{position:fixed;inset:0;z-index:1000;width:100%;max-width:none;height:100dvh;padding:12px;margin:0;background:var(--bg);grid-template-rows:auto auto minmax(0,1fr);gap:10px 16px;overflow:hidden}
.precision-workspace .precision-bar{display:flex;align-items:center;gap:12px;grid-column:1/-1;min-width:0}.precision-bar strong{font-size:14px}.precision-bar span[role=status]{flex:1;font-size:12px;color:var(--gold)}.precision-bar button{font-size:12px;white-space:nowrap;padding:6px 12px;min-height:40px}
.precision-workspace .studio-steps{grid-row:2;padding:0;border:0}.precision-workspace .studio-steps button{padding:6px 10px;min-height:40px}
.precision-workspace .studio-controls{grid-row:3;overflow:auto;height:100%;overscroll-behavior:contain}.precision-workspace .studio-workspace{grid-row:3;display:flex;flex-direction:column;min-height:0;height:100%;overflow:auto}.precision-workspace .preview-shell{flex:1;min-height:180px;overscroll-behavior:contain}.precision-workspace .preview-stage{margin:auto}
.precision-workspace .scene-toolbar{gap:6px;margin-bottom:8px}.precision-workspace .ui-scale-help,.precision-workspace #ui-scale-help,.precision-workspace .preview-notes{display:none}.precision-workspace .ui-scale-control{grid-template-columns:60px 1fr}.precision-workspace .ui-scale-control p{font-size:10px}.precision-workspace .preview-options{margin:6px 0}.precision-workspace .selected-feature{padding:4px 10px;margin:4px 0}.precision-workspace .selected-feature p,.precision-workspace .selected-feature a{display:none}.precision-workspace .editor-toolbar{margin-bottom:6px}.precision-workspace .editor-toolbar p{font-size:11px}.precision-workspace .module-cards{max-height:none}.precision-workspace.controls-collapsed{grid-template-columns:minmax(0,1fr)}.controls-collapsed .studio-controls{display:none}
@media(max-width:760px){.studio-layout.precision-workspace{grid-template-columns:1fr;padding:6px;overflow:auto;grid-template-rows:auto auto auto minmax(400px,1fr)}.precision-workspace .precision-bar{flex-wrap:wrap;gap:4px}.precision-bar strong{flex:1}.precision-bar span[role=status]{flex-basis:100%;order:4}.precision-workspace .studio-controls{grid-row:3;max-height:32dvh}.precision-workspace .studio-workspace{grid-row:4;min-height:400px}.precision-workspace.controls-collapsed{grid-template-rows:auto auto minmax(400px,1fr)}.controls-collapsed .studio-workspace{grid-row:3}.precision-workspace .studio-steps{position:static}.editor-toolbar{flex-wrap:wrap}.editor-toolbar>div{flex-basis:100%}.editor-toolbar #fullscreen{grid-column:1}.precision-workspace .ui-scale-control{grid-template-columns:1fr}}
.background-options{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.background-options label{display:flex;align-items:center;gap:8px;margin:0;font-size:12px}.background-options select{width:170px;padding:5px;min-height:36px;margin:0}.background-options p{margin:0;flex:1;font-size:11px}.precision-workspace .background-options p{font-size:10px}.precision-workspace #fullscreen{display:none}

/* Canvas-first layout editing. Controls are HTML; the game surface stays captured pixels. */
.studio-layout.layout-workspace{grid-template-columns:minmax(0,1fr);width:calc(100% - 32px);max-width:1920px}
.layout-workspace .studio-controls{display:none}
.layout-navigation{display:flex;align-items:center;gap:12px;margin:6px 0 12px}
.layout-navigation #layout-tabs{flex:1}.layout-navigation .studio-tabs{border:0;margin:0;max-width:380px}
.layout-navigation button{font-size:13px}.layout-navigation .studio-tabs button{min-height:44px}
.bar-picker{display:flex;gap:6px;align-items:center;flex-wrap:wrap;padding:10px 12px;background:#141d23;border:1px solid var(--line);border-radius:7px 7px 0 0}
.bar-picker:before{content:"EDIT A BAR";font-size:10px;font-weight:700;letter-spacing:.1em;color:var(--muted);margin-right:10px}
.bar-picker button{min-height:40px;padding:5px 18px;font-size:13px;background:transparent}
.bar-picker button[aria-pressed=true]{background:var(--gold);border-color:var(--gold);color:var(--bg);font-weight:700}
.bar-picker .bar-off{border-style:dashed}
.canvas-workspace{position:relative;min-width:0}
.layout-workspace .preview-shell{border-top-left-radius:0;border-top-right-radius:0}
.layout-tools{position:absolute;z-index:10;top:14px;left:14px;width:296px;max-width:calc(100% - 28px);pointer-events:none}
.layout-tools #custom-layout{display:flex;flex-direction:column;gap:8px;pointer-events:none}
.layout-tools .frame-picker,.layout-inspector{pointer-events:auto;background:#10191ff5;border:1px solid #4b5d66;border-radius:8px;box-shadow:0 8px 25px #0006}
.frame-picker{display:flex;align-items:center;gap:12px;padding:8px 12px;font-size:11px;color:var(--muted);margin:0;white-space:nowrap}
.frame-picker select{width:0;flex:1;font-size:12px;min-height:40px;margin:0;padding:5px}
.layout-inspector{padding:14px;font-size:12px;max-height:calc(100dvh - 270px);overflow:auto;overscroll-behavior:contain}
.layout-inspector>header{display:flex;align-items:center;gap:10px;margin-bottom:10px}
.layout-inspector>header strong{font-size:15px;flex:1;overflow-wrap:anywhere}
.layout-inspector>header button{min-width:36px;min-height:36px;padding:0;font-size:22px;border:0;background:transparent;color:var(--muted)}
.layout-inspector h3{font-size:12px;font-weight:500;margin:0;color:var(--muted)}
.layout-inspector p{font-size:11px;margin:4px 0 10px;line-height:1.45;color:var(--muted)}
.layout-inspector details{border-top:1px solid var(--line);margin-top:10px;padding-top:2px}
.layout-inspector summary{min-height:40px;font-size:12px;padding:8px 0}
.layout-inspector button{font-size:12px}
.bar-shape{display:block;margin:0;padding:0;border:0;background:transparent}
.bar-arrangements{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:6px;margin:12px 0}
.bar-arrangements button{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:6px;padding:8px 4px;min-height:70px;font-size:11px}
.bar-arrangements button[aria-pressed=true],.bar-gaps button[aria-pressed=true]{border-color:var(--gold);background:#3b3223;color:var(--gold)}
.arrangement-icon{display:grid;grid-template-columns:repeat(var(--columns),1fr);gap:2px;max-height:30px;width:54px;height:30px;align-content:center;justify-items:center}
.arrangement-icon{grid-template-rows:repeat(var(--rows),1fr);gap:1px}.arrangement-icon i{display:block;background:currentColor;width:100%;max-width:7px;height:100%;max-height:5px;align-self:center;opacity:.8}
.bar-custom-row{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:10px 0}
.bar-custom-row label{font-size:12px;margin:0}
.bar-custom-row input[type=number]{flex:none;width:76px;min-width:76px;min-height:44px;padding:8px;font-size:15px;font-variant-numeric:tabular-nums}
.bar-size-label{display:flex;align-items:center;gap:12px;font-size:12px;margin:8px 0}
.bar-size-label select{width:0;flex:1;min-width:150px;margin:0;font-size:12px;min-height:44px;padding:8px}
.bar-gaps{display:grid;grid-template-columns:repeat(4,1fr);gap:4px}.bar-gaps button{padding:4px 0;font-size:10px;min-height:36px}
#bar-shape-reset{width:100%;min-height:40px}
.layout-inspector .frame-list{max-height:200px;overflow:auto}
.layout-workspace .studio-mover.bar-handle:not(.selected):not(.conflict){border-color:#b1c5cc40;background:transparent}
.layout-workspace .studio-mover.bar-handle:not(.selected):not(.conflict) span{opacity:0}
.layout-workspace .studio-mover.bar-handle:hover span,.layout-workspace .studio-mover.bar-handle:focus-visible span{opacity:1}
.layout-workspace .character-area:not(.conflict){border-color:#ccd6dc18}
.layout-workspace .character-area:not(.conflict)>span,.layout-workspace .character-area:not(.conflict)>small{display:none}
.layout-workspace .character-area:not(.conflict):before{opacity:.3}
.layout-workspace .scene-toolbar{grid-template-columns:150px 170px 210px minmax(250px,1fr);align-items:start}
.layout-workspace .ui-scale-control{grid-column:auto;display:block}
.layout-workspace .ui-scale-control>label{display:block}.layout-workspace #ui-scale-help{display:none}
.layout-workspace .ui-scale-control p{font-size:10px;margin:4px 0 0}
.layout-workspace .ui-scale-inputs{gap:6px}.layout-workspace .ui-scale-inputs input[type=number]{width:66px}
.layout-workspace .ui-scale-inputs span{display:none}
.layout-workspace .preview-options #edit-positions{display:none}
.precision-workspace.layout-workspace{width:100%;max-width:none;padding:8px 12px;grid-template-rows:auto auto minmax(0,1fr)}
.precision-workspace.layout-workspace .studio-workspace{grid-column:1;grid-row:3;overflow:hidden}
.precision-workspace .canvas-workspace{flex:1;min-height:0;display:flex;flex-direction:column;overflow:hidden}
.precision-workspace .canvas-workspace>.preview-shell{flex:1;min-height:0}
.precision-workspace.layout-workspace .layout-navigation{margin:0 0 6px}
.precision-workspace.layout-workspace .editor-toolbar>div,.precision-workspace.layout-workspace .preview-notes,.precision-workspace.layout-workspace .background-options,.precision-workspace.layout-workspace .selected-feature{display:none}
.precision-workspace.layout-workspace .editor-toolbar{position:absolute;right:275px;top:8px;z-index:2;margin:0}
.precision-workspace.layout-workspace .preview-caption{padding:2px 0}
.precision-workspace.layout-workspace .bar-picker{padding:6px 12px}
.precision-workspace.layout-workspace .layout-inspector{max-height:calc(100dvh - 290px)}
.layout-workspace[hidden],.layout-navigation[hidden],.bar-picker[hidden],.layout-tools[hidden],.layout-inspector[hidden],.bar-shape[hidden]{display:none}
@media(max-width:1100px){.layout-workspace .scene-toolbar{grid-template-columns:1fr 1fr 1.3fr}.layout-workspace .ui-scale-control{grid-column:1/-1;display:grid;grid-template-columns:70px 1fr}.layout-workspace .ui-scale-control p{grid-column:1/-1}.layout-tools{width:276px}.precision-workspace.layout-workspace .editor-toolbar{position:static}.precision-workspace.layout-workspace .editor-toolbar>div{display:block}}
@media(max-width:760px){
 .studio-layout.layout-workspace{width:calc(100% - 16px);gap:8px}
 .layout-navigation{flex-wrap:wrap;gap:6px}.layout-navigation #layout-tabs{flex-basis:100%}.layout-navigation .studio-tabs{max-width:none}.layout-navigation>button{flex:1;padding:6px 8px;font-size:12px}
 .bar-picker{gap:4px;padding:8px}.bar-picker:before{display:none}.bar-picker button{flex:1;min-width:65px;padding:5px 8px;font-size:12px}
 .layout-tools{position:relative;top:auto;left:auto;width:100%;max-width:none;order:2;margin-top:8px}
 .canvas-workspace{display:flex;flex-direction:column}.layout-tools #custom-layout{gap:6px}
 .layout-inspector{max-height:420px}.bar-arrangements{grid-template-columns:repeat(6,minmax(0,1fr))}.bar-arrangements button{min-height:64px}.arrangement-icon{max-width:40px}
 .bar-size-label select{min-width:150px}.layout-workspace .preview-options{font-size:11px}
 .precision-workspace.layout-workspace{grid-template-rows:auto auto minmax(0,1fr);overflow:hidden;height:100dvh}
 .precision-workspace.layout-workspace .studio-workspace{grid-row:3;min-height:0}
 .precision-workspace.layout-workspace .precision-bar strong,.precision-workspace.layout-workspace .precision-bar span[role=status],.precision-workspace.layout-workspace .editor-toolbar,.precision-workspace.layout-workspace .ui-scale-control p,.precision-workspace.layout-workspace .preview-caption,.precision-workspace.layout-workspace .selected-feature{display:none}
 .precision-workspace.layout-workspace .precision-bar{flex-wrap:nowrap;justify-content:space-between}
 .precision-workspace.layout-workspace .scene-toolbar{grid-template-columns:1fr 1fr;gap:4px}.precision-workspace.layout-workspace .scene-toolbar label:last-child{grid-column:auto}
 .precision-workspace.layout-workspace .canvas-workspace{overflow:auto;display:block}.precision-workspace.layout-workspace .canvas-workspace>.preview-shell{min-height:160px}
 .precision-workspace.layout-workspace .layout-inspector{max-height:32dvh}
 .precision-workspace.layout-workspace .preview-options{flex:none}
}
@media(prefers-reduced-motion:reduce){.layout-inspector,.studio-mover{transition:none}}


/* Layout occupies the browser viewport; native fullscreen remains optional. */
body:has(.layout-workspace) .site-header,body:has(.layout-workspace) .studio-heading,body:has(.layout-workspace) .studio-fallback{display:none}
.studio-layout.layout-workspace{height:100dvh;min-height:0;overflow:hidden;padding-block:8px;grid-template-rows:auto auto minmax(0,1fr);gap:8px}
.layout-workspace .precision-bar{display:flex;grid-column:1/-1;grid-row:1;align-items:center;gap:12px;min-height:44px}
.layout-workspace:not(.precision-workspace) #workspace-controls,.layout-workspace:not(.precision-workspace) #exit-fullscreen{display:none}
.layout-workspace .precision-bar span[role=status]{white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-right:230px}
.layout-workspace .studio-steps{grid-row:2;margin:0;padding:0;border:0;position:static}
.layout-workspace .studio-steps button{padding:6px 10px;min-height:40px}
.layout-workspace .studio-workspace{grid-row:3;display:flex;flex-direction:column;height:100%;min-height:0;overflow:hidden}
.layout-workspace .canvas-workspace{flex:1;min-height:0;display:flex;flex-direction:column;overflow:hidden}
.layout-workspace .canvas-workspace>.preview-shell{flex:1;min-height:0}
.layout-workspace .preview-stage{margin:auto}
.layout-workspace .editor-toolbar{position:absolute;right:16px;top:8px;z-index:2;margin:0}
.layout-workspace .editor-toolbar>div,.layout-workspace .preview-notes,.layout-workspace .background-options,.layout-workspace .selected-feature{display:none}
.layout-workspace .layout-navigation{margin:0 0 6px}
.layout-workspace .preview-options{margin:6px 0}
.layout-workspace .preview-caption{padding:2px 0}
.layout-workspace .layout-inspector{max-height:calc(100dvh - 370px)}
.precision-workspace.layout-workspace .precision-bar span[role=status]{margin-right:160px}
@media(max-width:1100px){.layout-workspace .precision-bar strong{font-size:12px}.layout-workspace .scene-toolbar{margin-bottom:6px}.precision-workspace.layout-workspace .editor-toolbar{position:absolute}.layout-workspace .layout-inspector{max-height:calc(100dvh - 410px)}}
@media(max-width:760px){
 .studio-layout.layout-workspace:not(.precision-workspace){height:auto;min-height:100dvh;overflow:visible;grid-template-rows:auto auto auto}
 .layout-workspace:not(.precision-workspace) .studio-workspace{height:auto;overflow:visible}
 .layout-workspace .precision-bar{flex-wrap:wrap;gap:4px}.layout-workspace .precision-bar strong{flex-basis:100%}
 .layout-workspace .precision-bar span[role=status]{margin:0;flex-basis:100%;font-size:11px}
 .layout-workspace .editor-toolbar{position:static;margin:4px 0;display:flex;justify-content:flex-end}
 .layout-workspace .scene-toolbar{grid-template-columns:1fr 1fr}
 .layout-workspace .scene-toolbar label:last-child{grid-column:1/-1}
 .layout-workspace .canvas-workspace{overflow:visible;display:flex}
 .layout-workspace .canvas-workspace>.preview-shell{flex:none;min-height:0}
 .layout-workspace .layout-inspector{max-height:420px}
 .layout-workspace .preview-caption{padding:8px 0}
 .precision-workspace.layout-workspace .editor-toolbar{position:static}
 .precision-workspace.layout-workspace .canvas-workspace{overflow:auto;display:block}
 .precision-workspace.layout-workspace .layout-inspector{max-height:32dvh}
}

@media(min-width:761px){html:has(.layout-workspace){overflow:hidden}}

`;
