import {studioControl} from "./studio-test-workflow.mjs";
import {test,expect} from "@playwright/test";
import {readFileSync} from "node:fs";
import {createEngine} from "./pack-engine.mjs";
import {sourcePaths} from "./pack-sources.mjs";
const engine=()=>createEngine(sourcePaths.map(p=>readFileSync(new URL("../"+p,import.meta.url),"utf8")));
const ready=page=>expect(page.locator("#game-preview")).toHaveAttribute("data-preview-ready","true");
test("all movers are discoverable and chat is an authentic visible sample",async({page})=>{
 await page.goto("/studio");await ready(page);
 await page.locator("#edit-positions").click();await ready(page);
 const painted=JSON.parse(await page.locator("#game-preview").getAttribute("data-painted-groups"));
 expect(painted).toContain("chat");expect(painted).toContain("stance");expect(painted).not.toContain("bags");
 for(const key of ["chat","castfocus","casttarget","loot","questtimers"])
  await expect(page.locator('#mover-layer [data-group="'+key+'"]')).toBeVisible();
 await page.locator('#mover-layer [data-group="questtimers"]').click({position:{x:4,y:4}});await ready(page);
 await expect(page.locator("#frame-group")).toHaveValue("questtimers");
 await expect(page.locator("#undo")).toBeDisabled();
 await page.getByText("All movable frames, including inactive groups",{exact:true}).click();
 const target=page.locator('#frame-list [data-group="casttarget"]');
 await target.focus();await page.keyboard.press("Enter");await ready(page);
 await expect(page.locator("#frame-group")).toHaveValue("casttarget");
 expect(JSON.parse(await page.locator("#game-preview").getAttribute("data-painted-groups"))).toContain("casttarget");
 await studioControl(page,"game-preview");await page.locator("#game-preview").focus();const before=await page.locator("#geometry").innerText();
 await page.keyboard.press("ArrowRight");await expect(page.locator("#geometry")).not.toHaveText(before);
 await studioControl(page,"undo");await page.locator("#undo").click();await expect(page.locator("#geometry")).toHaveText(before);
 await studioControl(page,"show-conditional");await page.locator("#show-conditional").check();await ready(page);
 expect(JSON.parse(await page.locator("#game-preview").getAttribute("data-painted-groups"))).toContain("loot");
});
test("conflicting invisible footprints identify their neighbors and remain highlighted",async({page})=>{
 const e=engine(),p=e.call("Bundled","centered");
 p.adjustments={positions:{main:{point:"BOTTOMLEFT",relativePoint:"BOTTOMLEFT",x:500,y:100},player:{point:"BOTTOMLEFT",relativePoint:"BOTTOMLEFT",x:500,y:100}}};
 await page.goto("/studio");await ready(page);
 await studioControl(page,"import-code");await page.locator("#import-code").fill(e.call("Encode",p));await studioControl(page,"import");await page.locator("#import").click();await ready(page);
 await expect(page.locator("#fit-conflicts")).toContainText(/clearance from/);
 await expect(page.locator("#mover-layer .conflict")).not.toHaveCount(0);
 await expect(page.locator("#export")).toBeDisabled();
 await studioControl(page,"fit-conflicts");
 const conflict=page.locator("#fit-conflicts button").first(),key=await conflict.getAttribute("data-group");
 await conflict.click();await expect(page.locator("#frame-group")).toHaveValue(key);
 await studioControl(page,"show-movers");await page.locator("#show-movers").uncheck();await ready(page);
 await expect(page.locator("#mover-layer .conflict").first()).toBeVisible();
});
test("imported viewport and per-component coverage survive export without blanking unrelated UI",async({page})=>{
 const e=engine(),p=e.call("Bundled","centered");p.viewport={width:2560,height:1440};p.profile.nameplates={adaptiveNames:false};
 await page.goto("/studio");await ready(page);
 await studioControl(page,"import-code");await page.locator("#import-code").fill(e.call("Encode",p));await studioControl(page,"import");await page.locator("#import").click();await ready(page);
 await expect(page.locator("#viewport")).toHaveValue("2560x1440");
 await expect(page.locator("#game-preview")).toHaveAttribute("width","2560");
 expect(JSON.parse(await page.locator("#game-preview").getAttribute("data-painted-groups"))).toContain("chat");
 expect(JSON.parse(await page.locator("#game-preview").getAttribute("data-painted-groups"))).toContain("main");
 await studioControl(page,"export");await page.locator("#export").click();
 expect(e.call("Decode",await page.locator("#result-code").inputValue()).viewport).toEqual(p.viewport);
 await studioControl(page,"activity");await page.locator("#activity").selectOption("town");await ready(page);
 expect(JSON.parse(await page.locator("#game-preview").getAttribute("data-painted-groups"))).toContain("bags");
});
test("character clearance follows the viewport and reports personal obstructions",async({page})=>{
 await page.goto("/studio");await ready(page);
 const zone=page.locator('[data-character-area="true"]');await expect(zone).toBeVisible();
 await expect(zone).toContainText("Your character · screen center");
 const center=async()=>{const z=await zone.boundingBox(),c=await page.locator("#game-preview").boundingBox();expect(Math.abs(z.x+z.width/2-c.x-c.width/2)).toBeLessThan(2);expect(Math.abs(z.y+z.height/2-c.y-c.height/2)).toBeLessThan(2);};
 await center();await page.locator("#device").selectOption("handheld");await ready(page);await center();
 const e=engine(),p=e.call("Bundled","centered");
 p.adjustments={positions:{player:{point:"BOTTOMLEFT",relativePoint:"BOTTOMLEFT",x:900,y:520}}};
 await studioControl(page,"import-code");await page.locator("#import-code").fill(e.call("Encode",p));
 await studioControl(page,"import");await page.locator("#import").click();await ready(page);
 await studioControl(page,"fit-conflicts");await expect(page.locator("#fit-conflicts")).toContainText("Character viewing area");
 await expect(zone).toHaveClass(/conflict/);await expect(page.locator("#export")).toBeDisabled();
 await page.locator('#fit-conflicts [data-group="player"]').click();
 await page.locator("#reset-frame").click();await ready(page);
 await expect(zone).not.toHaveClass(/conflict/);await studioControl(page,"export");await expect(page.locator("#export")).toBeEnabled();
});
