import { previewStyles } from "./preview-styles.mjs";
export const styles = `
:root{color-scheme:dark;--bg:#0c1016;--panel:#121923;--line:#29323e;--muted:#a2aebb;--ink:#e6ebf5;--gold:#e7c481;--accent:#69cbee;font-family:Arial,Helvetica,sans-serif;color:var(--ink);background:var(--bg)}
*{box-sizing:border-box}html{scroll-behavior:smooth;scroll-padding-top:28px}body{margin:0}a{color:inherit;text-decoration:none}button{font:inherit}a,button,summary{-webkit-tap-highlight-color:transparent}button{cursor:pointer}svg{width:22px;height:22px;flex-shrink:0}
a:focus-visible,button:focus-visible,summary:focus-visible,[tabindex]:focus-visible{outline:2px solid var(--gold);outline-offset:5px}a:hover{color:#fff}p{line-height:1.7}h1,h2,h3,p{margin-top:0}code,kbd,.eyebrow,.for-forever,.preview-disclosure,.showcase-top,.showcase-footer,.feature-number{font-family:Consolas,"Liberation Mono",monospace}
.wrap{width:min(1320px,calc(100% - 96px));margin-inline:auto}.skip{position:fixed;left:20px;top:-70px;background:var(--gold);color:#111;padding:15px;z-index:100}.skip:focus{top:15px}
.site-header{height:94px;border-bottom:1px solid var(--line);display:flex;align-items:center;gap:25px;padding:0 48px;max-width:1600px;margin:auto}
.brand{display:flex;align-items:center;gap:12px;font-size:27px;font-weight:800;letter-spacing:-1.2px}.brand svg{width:32px;height:32px;color:var(--gold)}.brand-ui{color:var(--gold)}.header-divider{height:22px;width:1px;background:var(--line)}.for-forever{font-size:10px;letter-spacing:1.6px;color:var(--muted)}
.site-header nav{display:flex;gap:30px;margin-left:auto;font-size:13px}.site-header nav a{padding:15px 0;color:#bec7d4}.source-link{border:1px solid #414a56;padding:11px 16px;font-size:12px;display:flex;gap:25px}.source-link:hover{background:var(--panel);border-color:var(--gold)}
.hero{display:grid;grid-template-columns:1.35fr 1fr;gap:40px;padding-block:70px 48px;align-items:end}.eyebrow{display:flex;align-items:center;gap:10px;letter-spacing:1.6px;font-size:10px;line-height:1.6;color:var(--gold);font-weight:400}.slash{color:#586575;margin:0 3px}.status-dot{height:6px;width:6px;background:var(--gold);display:inline-block;flex-shrink:0}
h1{font-size:clamp(42px,4.4vw,65px);line-height:1.06;letter-spacing:-2.7px;margin:24px 0 0;font-weight:750}h1>span{color:#91a0b2}h2{font-size:36px;line-height:1.15;letter-spacing:-1.4px;font-weight:600}h3{font-weight:600}.hero-intro{padding-left:32px}.hero-intro p{font-size:15px;color:#b6c0ce;margin-bottom:24px}.hero-actions{display:flex;align-items:center;gap:24px;flex-wrap:wrap}
.button{display:inline-flex;align-items:center;justify-content:space-between;gap:30px;padding:15px 20px;font-size:12px;line-height:1.3;font-weight:700;min-height:48px}.primary{background:var(--gold);color:#141619;border:1px solid var(--gold)}.primary:hover{background:#f5d697;color:#101218}.button svg{width:18px;height:18px}.quiet-link{font-size:12px;display:inline-flex;gap:22px;align-items:center;border-bottom:1px solid #556172;padding:10px 0}.quiet-link span{color:var(--gold)}
.showcase{border:1px solid #3c4756;box-shadow:0 25px 70px #0004;scroll-margin-top:24px}.showcase-top{height:45px;display:flex;align-items:center;justify-content:space-between;padding:0 20px;background:#151d28;border-bottom:1px solid var(--line)}.showcase-top h2{display:flex;align-items:center;gap:10px;font-family:inherit;font-size:10px;letter-spacing:1.3px;font-weight:400;margin:0}.showcase-top svg{width:16px;height:16px;color:var(--gold)}.preview-disclosure{font-size:10px;color:#a9b5c4;letter-spacing:.2px}
.toolbar{display:none;justify-content:space-between;background:#111720;border-bottom:1px solid var(--line);gap:12px}.enhanced .toolbar{display:flex}.tabs{display:flex}.tabs button{border:0;border-right:1px solid var(--line);background:transparent;color:#a3afbe;padding:17px 21px;display:flex;align-items:center;gap:9px;font-size:12px;position:relative;white-space:nowrap}.tabs button svg{width:17px;height:17px}.tabs button[aria-selected=true]{background:#1d2733;color:#f3d9a2}.tabs button[aria-selected=true]:after{content:"";height:2px;background:var(--gold);position:absolute;bottom:0;left:0;right:0}.tabs button:hover{background:#1b2530}
.accent-picker{display:flex;align-items:center;padding:0 14px;gap:2px}.accent-picker>span{font:9px Consolas,monospace;color:#9aa8bb;letter-spacing:1px;margin-right:9px}.swatch{border:1px solid transparent;background:transparent;padding:8px;width:34px;height:34px;display:grid;place-items:center}.swatch i{display:block;background:var(--swatch);width:13px;height:13px}.swatch[aria-pressed=true]{border-color:#8191a4}.mage{--swatch:#69cbee}.warlock{--swatch:#ad95df}.druid{--swatch:#ed995c}.warrior{--swatch:#c8ad8a}
.preview-area{--accent:#69cbee;--accent-dim:#234b5c}.preview-area[data-theme=warlock]{--accent:#ad95df;--accent-dim:#403253}.preview-area[data-theme=druid]{--accent:#ed995c;--accent-dim:#633e26}.preview-area[data-theme=warrior]{--accent:#c8ad8a;--accent-dim:#534737}.preview-panel{display:grid;grid-template-columns:minmax(0,1fr) 285px;min-height:490px}[hidden]{display:none!important}
.inspector{border-left:1px solid var(--line);padding:31px 27px;background:#151b25;display:flex;flex-direction:column}.inspector .eyebrow{font-size:9px;letter-spacing:1px;color:var(--accent)}.inspector h3{font-size:27px;line-height:1.12;letter-spacing:-.8px;margin:18px 0}.inspector>p{font-size:13px;color:#aebaca;margin-bottom:15px}.inspector ol{padding:0;margin:0;list-style:none}.inspector li{display:flex;gap:12px;padding:16px 0;border-top:1px solid #2b3541}.inspector li>span{font:10px Consolas,monospace;color:var(--accent);padding-top:2px}.inspector li b{font-size:12px;font-weight:500}.inspector li p{font-size:11px;color:#99a8bb;margin:5px 0 0;line-height:1.6}.command{display:flex;flex-direction:column;gap:7px;padding:13px 14px;background:#0c1118;border:1px solid var(--line);margin-top:auto}.command span{font:8px Consolas,monospace;letter-spacing:1.4px;color:#93a2b5}.command code{font-size:12px;color:var(--accent)}.detail-link{display:flex;align-items:center;justify-content:space-between;font-size:10px;color:#c6d0df;padding-top:17px}.detail-link svg{width:15px;height:15px}
.showcase-footer{padding:13px 20px;display:flex;justify-content:space-between;border-top:1px solid var(--line);background:#0e141c;font-size:9px;letter-spacing:.7px;color:#a8b5c6}.showcase-footer i{display:inline-block;width:5px;height:5px;background:#8fab8e;margin-right:8px}.showcase-footer>span:last-child{font-family:Arial,sans-serif;letter-spacing:.1px;font-size:11px}.no-script{padding:20px}.no-script a{text-decoration:underline}
.features-section{padding:98px 0 90px}.section-heading{display:flex;justify-content:space-between;align-items:end;gap:40px;margin-bottom:37px}.section-heading h2{margin:20px 0 0}.section-heading>p{font-size:13px;color:#a8b5c6;margin:0 0 4px}.feature-lines{border-top:1px solid #35404e}.feature-lines>a{display:grid;grid-template-columns:35px 44px 1fr 25px;align-items:center;gap:24px;padding:25px 8px;border-bottom:1px solid var(--line);transition:background .15s}.feature-lines>a:hover{background:#151c25}.feature-number{font-size:11px;color:#8190a3}.feature-lines svg{color:var(--gold);width:27px;height:27px}.feature-lines h3{font-size:19px;margin-bottom:6px;letter-spacing:-.2px}.feature-lines p{font-size:14px;color:#9eacbd;margin:0}.feature-arrow{color:var(--gold);font-size:20px}
.setup-section{border-block:1px solid var(--line);background:#141b25}.start-grid{padding-block:66px;display:grid;grid-template-columns:1fr .8fr;gap:100px}.start-grid h2{margin:20px 0}.start-grid>div>p{max-width:440px;color:#abb7c7;font-size:13px;margin-bottom:25px}.start-grid .release-note{font-size:10px;line-height:1.8;margin:18px 0 0;padding-left:16px;position:relative}.release-note .status-dot{position:absolute;top:6px;left:0;width:4px;height:4px}
.start-steps{padding:0;margin:0;list-style:none;align-self:center}.start-steps li{display:flex;gap:24px;padding:24px 0;border-bottom:1px solid var(--line)}.start-steps li:first-child{padding-top:0}.start-steps li:last-child{border:0;padding-bottom:0}.start-steps li>span{font:12px Consolas,monospace;color:var(--gold);padding-top:3px}.start-steps h3{font-size:16px;margin-bottom:8px}.start-steps p{font-size:12px;line-height:1.7;color:#a6b4c7;margin:0}.start-steps code,.faq code{color:#dae4f2;background:#1b2634;padding:2px 4px;font-size:11px;white-space:nowrap}
.faq{display:grid;grid-template-columns:1fr 1.3fr;gap:70px;padding-block:80px}.faq h2{font-size:28px;margin-top:20px}.faq-list details{border-bottom:1px solid var(--line)}.faq-list details:first-child{border-top:1px solid var(--line)}.faq summary{font-size:14px;cursor:pointer;list-style:none;display:flex;justify-content:space-between;gap:20px;padding:21px 0}.faq summary::-webkit-details-marker{display:none}.faq summary span{color:var(--gold);font-size:18px;line-height:16px}.faq details[open] summary span{transform:rotate(45deg)}.faq details p{font-size:14px;color:#a7b6ca;max-width:540px;padding-right:30px;margin-bottom:24px}.faq p a{text-decoration:underline;color:var(--ink)}
footer{border-top:1px solid var(--line);display:flex;align-items:center;gap:38px;padding-block:32px}footer p{font-size:11px;margin:0;color:#bdc8d7}footer small{font-size:9px;color:#8290a3}footer>div{display:flex;gap:24px;margin-left:auto;font-size:11px;color:#afbccd}
@media(min-width:1600px){.hero{padding-top:85px}}
@media(max-width:1100px){.wrap{width:calc(100% - 48px)}.site-header{padding:0 24px;gap:18px}.for-forever{display:none}.header-divider{display:none}.hero{gap:20px;grid-template-columns:1.1fr 1fr}.hero-intro{padding-left:0}h1{font-size:48px}.hero-intro p{font-size:13px}.preview-panel{grid-template-columns:minmax(0,1fr) 240px}.inspector{padding:26px 20px}.tabs button{padding:17px 13px}.accent-picker>span{display:none}.start-grid{gap:55px}}
@media(max-width:800px){.hero{grid-template-columns:1fr;padding-top:44px;gap:25px}.hero-intro p{font-size:14px}.hero-intro p br{display:none}.hero-intro p{max-width:460px}.hero-intro{display:flex;justify-content:space-between;gap:24px;align-items:start}.hero-actions{flex-direction:column;gap:6px;align-items:start;flex-shrink:0}.preview-panel{grid-template-columns:1fr}.inspector{border-left:0;border-top:1px solid var(--line);display:grid;grid-template-columns:1fr 1fr;gap:0 24px}.inspector h3{grid-column:1;margin-bottom:12px}.inspector>p{grid-column:1}.inspector ol{grid-column:2;grid-row:1/4}.command{grid-column:1}.detail-link{grid-column:2;align-self:center;padding-top:0}.section-heading{align-items:start;flex-direction:column;gap:20px}.features-section{padding-block:66px}.start-grid{grid-template-columns:1fr;gap:40px}.faq{grid-template-columns:1fr;gap:20px;padding-block:55px}.faq h2{margin-bottom:10px}footer{gap:22px;flex-wrap:wrap}footer>div{margin-left:0}.desktop-break{display:none}}
@media(max-width:540px){.wrap{width:calc(100% - 32px)}.site-header{height:74px;padding:0 16px;gap:15px}.site-header nav{gap:16px;font-size:11px}.site-header nav a:first-child{display:none}.source-link{display:none}.brand{font-size:24px;gap:9px}.brand svg{width:27px;height:27px}.hero{padding-block:38px 28px}.hero .eyebrow{font-size:9px}h1{font-size:42px;letter-spacing:-1.9px;margin-top:20px}.hero-intro{display:block}.hero-intro p{font-size:13px;margin-bottom:20px}.hero-actions{flex-direction:row;align-items:center;gap:20px}.button{padding:14px 15px;gap:15px;font-size:11px}.quiet-link{font-size:11px}.showcase-top{padding:12px;height:auto;align-items:start;gap:8px}.showcase-top h2{font-size:8px;letter-spacing:.6px}.preview-disclosure{font-size:8px;max-width:105px;line-height:1.5;text-align:right}.toolbar{flex-wrap:wrap;gap:0}.tabs{width:100%}.tabs button{flex:1;justify-content:center;font-size:10px;padding:15px 6px;gap:5px}.tabs button svg{width:14px;height:14px}.accent-picker{width:100%;padding:5px 9px;justify-content:flex-end;border-top:1px solid var(--line)}.accent-picker>span{display:block;margin-right:auto;font-size:8px}.swatch{width:32px;height:30px}.inspector{grid-template-columns:1fr;padding:24px;gap:0}.inspector .eyebrow,.inspector h3,.inspector>p,.inspector ol,.command,.detail-link{grid-column:1;grid-row:auto}.inspector h3 br{display:none}.inspector h3{font-size:25px}.inspector h3 br:after{content:" "}.inspector li{padding:13px 0}.inspector .command{margin-top:10px}.detail-link{padding-top:16px}.showcase-footer{padding:12px;font-size:8px;letter-spacing:.2px}.showcase-footer>span:last-child{display:none}h2{font-size:29px}.feature-lines>a{grid-template-columns:25px 28px 1fr 12px;gap:13px;padding:22px 0}.feature-lines h3{font-size:15px}.feature-lines p{font-size:11px}.feature-lines svg{width:23px;height:23px}.feature-number{font-size:9px}.feature-arrow{font-size:15px}.start-grid{padding-block:45px}.faq summary{font-size:12px}.faq details p{padding-right:0}footer{gap:20px}footer p{font-size:10px;max-width:215px}footer small{font-size:8px}footer>div{width:100%;padding-top:6px}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}*{transition:none!important}}
` + previewStyles;
