export const styles = `
:root{color-scheme:dark;--bg:#141916;--paper:#ececdf;--muted:#b1b9ac;--accent:#c2da98;--line:#354037}
*{box-sizing:border-box}html{scroll-behavior:smooth;scroll-padding-top:2rem}body{margin:0;background:var(--bg);color:var(--paper);font:16px/1.6 system-ui,-apple-system,"Segoe UI",sans-serif}a{color:inherit;text-decoration:none}a:focus-visible{outline:2px solid var(--accent);outline-offset:6px}a:hover{color:var(--accent)}
header,main,footer{max-width:1280px;margin:auto}header{padding:30px 6%;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--line)}.wordmark{font-size:36px;line-height:1;font-weight:800;letter-spacing:-3px}.wordmark span{color:var(--accent);padding-left:4px}nav{display:flex;gap:32px;font-size:13px}.skip{position:absolute;left:10px;top:-60px;background:var(--accent);color:var(--bg);padding:10px;z-index:5}.skip:focus{top:10px}
.hero{position:relative;isolation:isolate;overflow:hidden;padding:78px 6% 0}.eyebrow,.section-label,.hero-foot,.map-label{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:11px;letter-spacing:1.5px}.eyebrow{display:flex;align-items:center;gap:10px;color:var(--accent)}.dot{width:6px;height:6px;background:var(--accent);border-radius:50%}h1{font-size:clamp(54px,7.8vw,98px);line-height:1.06;letter-spacing:-5px;font-weight:450;max-width:780px;margin:32px 0}h1 em{font-family:Georgia,serif;font-weight:400;color:var(--accent)}.intro{font-size:18px;color:var(--muted);margin:28px 0 32px}.button{display:inline-flex;gap:36px;align-items:center;justify-content:space-between;background:var(--accent);color:#17201a;padding:13px 22px;border-radius:3px;font-size:13px;font-weight:650}.button:hover{background:#d6e9b7;color:#17201a}.terrain{position:absolute;z-index:-1;right:-130px;top:40px;width:650px;color:#455b40;opacity:.7}.terrain svg{width:100%;height:auto}.trail{color:var(--accent)}.map-label{position:absolute;right:175px;bottom:110px;font-size:9px;color:var(--muted)}.hero-foot{display:flex;justify-content:space-between;gap:20px;border-top:1px solid var(--line);color:var(--muted);margin-top:86px;padding:22px 0;font-size:10px}
.product{padding:70px 6% 80px;background:#1a211c;border-bottom:1px solid var(--line);border-top:1px solid var(--line)}.section-label{color:var(--accent);display:block;margin-bottom:28px}.product-grid{display:grid;grid-template-columns:1fr 1fr;gap:90px}.product-title{display:flex;gap:18px;align-items:center}h2{font-size:44px;line-height:1.15;font-weight:450;letter-spacing:-1.6px;margin:0}.badge{font-size:9px;letter-spacing:1px;border:1px solid #506548;color:var(--accent);padding:4px 8px;border-radius:3px}.lead{font-size:21px;margin:24px 0 12px}p{color:var(--muted);max-width:480px}.actions{display:flex;flex-wrap:wrap;gap:24px;align-items:center;margin:30px 0 20px}.text-link{font-size:13px;border-bottom:1px solid var(--line);padding:5px 0}.download-note{font-size:12px;line-height:1.7;max-width:390px}.features article{display:flex;gap:24px;padding:24px 0;border-top:1px solid var(--line)}.features article:first-child{padding-top:4px;border-top:0}.features article>span{font:11px ui-monospace,monospace;color:var(--accent);padding-top:6px}h3{font-size:18px;font-weight:500;margin:0}.features p{font-size:14px;margin:9px 0 0;max-width:340px}.closing{padding:76px 6% 84px}.closing h2{font-size:clamp(30px,4vw,44px);margin-bottom:26px}footer{padding:28px 6%;border-top:1px solid var(--line);display:flex;align-items:center;gap:40px}footer p{font-size:11px;margin:0}footer>a:last-child{margin-left:auto;font-size:12px}
@media(max-width:760px){header{padding:24px 6%}nav{gap:20px}.hero{padding-top:52px}h1{letter-spacing:-3px}.terrain{right:-310px;top:65px;opacity:.3}.hero-foot{margin-top:65px;font-size:9px;letter-spacing:.5px}.product-grid{grid-template-columns:1fr;gap:38px}.product{padding-top:48px;padding-bottom:40px}.features article{padding:20px 0}.closing{padding-top:50px;padding-bottom:55px}footer{gap:24px}footer p{font-size:10px}footer>a:last-child{font-size:10px}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}
`;
